### ISSUE TITLE
Wrapping pathway names in the strip at the top of GSEA subplots

### ISSUE THREAD

**Issue by sg3451** [NicolasH2/gggsea#3]
Hello, is there a way to break the names of long pathways into multiple lines of text in the strips associated with each pathway results in gggsea. I love the tool but sometimes it is becoming hard to read the pathway names above the enrichment plots. 
Thanks in advance. 
Sujoy 
![pathway_crop2_011624](https://github.com/NicolasH2/gggsea/assets/75069069/3a363a7f-7655-4afe-8333-64eab6242cc1)
![pathway_crop1_011624](https://github.com/NicolasH2/gggsea/assets/75069069/2d35a6b1-c395-437e-afc5-f3c939a434a4)
![pathway_crop2_011624](https://github.com/NicolasH2/gggsea/assets/75069069/79ebed5b-42be-4c50-8c71-371b4074eaad)
![pathway_crop1_011624](https://github.com/NicolasH2/gggsea/assets/75069069/47e84b17-9c64-4f46-b4e2-d26aeb2efa95)

**Comment by NicolasH2** [comment]
Hi @sg3451 ,
thanks for the feedback. I have looked into it and changed the package to include this functionality. By default, the underscores will be replaced by spaces. The title will then receive an auto-linebreak. The number of characters before the line breaks is set to 20 by default, but can be adjusted as you like with the `titlelength` parameter (see below).

Does that solve the issue? You would have to remove the package with `remove.package("gggsea")` and re-install it in order to get that functionality.

E.g. 
```r
ggplot2::ggplot() + 
    geom_gsea(df2, titlelength = 5) +
    theme_gsea(7)
```

![gsea_titlebreak](https://github.com/NicolasH2/gggsea/assets/50340626/6eaef2b5-ec7c-4421-b137-c6b10a3190e7)

**Comment by sg3451** [comment]
Wow! It absolutely does! This is super helpful. Thanks very much indeed!
Sujoy
